services:
  nginx:
    image: nginx:1.27-alpine
    container_name: distributed-nginx
    ports:
      - "8008:8008"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - master1
      - master2
      # - master3
      # - master4

  master1:
    build:
      context: .
      dockerfile: master/Dockerfile.master_node
    container_name: master1
    environment:
      MASTER_ID: master1
      WORKERS_BOOTSTRAP: '[{"worker_id":"worker_1_1","url":"http://cpu_worker_1_1:9001","device_type":"cpu"},
                          {"worker_id":"worker_1_2","url":"http://cpu_worker_1_2:9001","device_type":"cpu"}]'


  master2:
    build:
      context: .
      dockerfile: master/Dockerfile.master_node
    container_name: master2
    environment:
      MASTER_ID: master2
      WORKERS_BOOTSTRAP: '[{"worker_id":"worker_2_1","url":"http://cpu_worker_2_1:9001","device_type":"cpu"},
                          {"worker_id":"worker_2_2","url":"http://cpu_worker_2_2:9001","device_type":"cpu"}]'

  cpu_worker_1_1:
    build:
      context: .
      dockerfile: workers/Dockerfile.cpu
    container_name: cpu_worker_1_1
    environment:
      - MODEL_PATH=/app/models/qwen2.5-0.5b
      - WORKER_ID=worker_1_1
      - MASTER_URL=http://master1:7000
      - SELF_URL=http://cpu_worker_1_1:9001
    ports:
      - "9001:9001"
    volumes:
      - ./models:/app/models:ro
    restart: unless-stopped
  
      

  cpu_worker_1_2:
      build:
        context: .
        dockerfile: workers/Dockerfile.cpu
      container_name: cpu_worker_1_2
      environment:
        - MODEL_PATH=/app/models/qwen2.5-0.5b
        - WORKER_ID=worker_1_2
        - MASTER_URL=http://master1:7000
        - SELF_URL=http://cpu_worker_1_2:9001
      ports:
        - "9002:9001"
      volumes:
        - ./models:/app/models:ro
      restart: unless-stopped
  cpu_worker_2_1:
      build:
        context: .
        dockerfile: workers/Dockerfile.cpu
      container_name: cpu_worker_2_1
      environment:
        - MODEL_PATH=/app/models/qwen2.5-0.5b
        - WORKER_ID=worker_2_1
        - MASTER_URL=http://master2:7000
        - SELF_URL=http://cpu_worker_2_1:9001
      ports:
        - "9003:9001"
      volumes:
        - ./models:/app/models:ro
      restart: unless-stopped
  cpu_worker_2_2:
      build:
        context: .
        dockerfile: workers/Dockerfile.cpu
      container_name: cpu_worker_2_2
      environment:
        - MODEL_PATH=/app/models/qwen2.5-0.5b
        - WORKER_ID=worker_2_2
        - MASTER_URL=http://master2:7000
        - SELF_URL=http://cpu_worker_2_2:9001
      ports:
        - "9004:9001"
      volumes:
        - ./models:/app/models:ro
      restart: unless-stopped

