# syntax=docker/dockerfile:1.6

FROM python:3.11-slim

WORKDIR /app

COPY requirements-master.txt ./requirements-master.txt
RUN --mount=type=cache,target=/root/.cache/pip,sharing=locked \
	pip install --upgrade pip setuptools wheel \
	&& pip install -r requirements-master.txt


COPY master ./master

CMD ["uvicorn", "master.master_app:app", "--host", "0.0.0.0", "--port", "7000"]
