FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir fastapi==0.110.0 uvicorn[standard]==0.27.0 pydantic==2.6.0 httpx==0.27.0


COPY master ./master

CMD ["uvicorn", "master.master_app:app", "--host", "0.0.0.0", "--port", "7000"]
